#!/bin/bash

# pass rtems to build RTEMS on cross-compiler
TARGET_ARCHITECTURE=${1:-linux}

# local build script for epics-containers ioc

set -xe

THIS_DIR=$(realpath $(dirname ${0}))
PROJECT=$(basename ${THIS_DIR})

ARGS="
--build-arg TARGET_ARCHITECTURE=${TARGET_ARCHITECTURE}
--build-arg TARGETARCH=amd64
--net host
"

for target in developer runtime ; do
    TAG=${PROJECT}-${TARGET_ARCHITECTURE}-${target}:local
    podman buildx build --target ${target} ${ARGS} -t ${TAG} .
done

# get the schema file from the developer container and save it locally
# it is called xxxxx.ioc.ibek.schema.json for project ioc-xxxxx
podman run ghcr.io/epics-containers/ioc-adaravis-linux-developer:local bash -c \
    'ibek ioc generate-schema /epics/links/ibek/*ibek.support.yaml' > \
    ${PROJECT#ioc-}.ibek.ioc.schema.json
